version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0.amd64
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - ~/application/kafka/zookeeper/data:/var/lib/zookeeper/data
      - ~/application/kafka/zookeeper/log:/var/lib/zookeeper/log
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:7.3.0.amd64
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ~/application/kafka/data:/var/lib/kafka/data
    ports:
      - 9092:9092
  kafdrop:
    image: obsidiandynamics/kafdrop:3.30.0
    depends_on:
      - kafka
    ports:
      - 9090:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:19092
  mongoDB:
    container_name: mongodb-batch-objects
    image: arm64v8/mongo:4.0
    platform: linux/arm64/v8
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 1024M
    environment:
      MONGO_INITDB_DATABASE: test-db
    volumes:
      - batch-objects:/var/lib/mongo/batch-objects
    ports:
      - "27018:27017"
volumes:
  batch-objects: